### ISSUE TITLE
always showing "Everything is fine."

### ISSUE THREAD

**Issue by zheeeng** [Bessonov/set-project-references#14]
Tried cli at project root and sub-package.

**Comment by Bessonov** [comment]
Hey @zheeeng , do you use npm, yarn or pnpm? Have you a reproduction example? Did you set up project references already?

**Comment by Bessonov** [comment]
Fell free to reopen if issue is still here.

**Comment by E0SelmY4V** [comment]
> Tried cli at project root and sub-package.

How did you solve the problem? I've been troubled by it too. 

Regardless of whether there is a `tsconfig.json` in my root directory, whether there is a `references` field in `tsconfig.json`, or whether there are some path in the field, in short, there is no other reaction except for "Everything is fine", and my tsconfig.json has not been updated.

Could it be that I have misunderstood the function of this tool?

**Comment by Bessonov** [comment]
@E0SelmY4V this tool is intended to be run after you add a local module as a dependency of another local module. It syncs TypeScript project references.

For example, you have:

```
packages/common/tsconfig.json
packages/package-a/tsconfig.json
...
"scripts": {
  "postinstall": "set-project-references --save"
},
```

Then after:

```
pnpm --filter package-a add common
```

you should find that it has synced your project references in `package-a/tsconfig.json`:

```
  "references": [
    { "path": "../common" }
  ]
```
